spring:
  application:
    name: ${APPLICATION_NAME:microservice}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
  healthcheck:
    enabled: ${EUREKA_HEALTHCHECK:true}

server:
  port: ${APPLICATION_PORT:8080}