spring:
  application:
    name: ${APPLICATION_NAME:microservice}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  healthcheck:
    enabled: true

server:
  port: ${APPLICATION_PORT:8080}